serverAddr = "router.kv9.ru"
serverPort = 7000

[[proxies]]
name = "Vorobiev Luci"
type = "tcp"
localPort = 80
remotePort = 8082

[[proxies]]
name = "Vorobiev SSH"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 2202
